# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'escolha',
                'verbose_name_plural': 'escolhas',
            },
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(default=b'1', max_length=1, verbose_name=b'Etapa')),
                ('name', models.CharField(default=b'Ideias', max_length=100, verbose_name=b'Nome da etapa')),
                ('header_txt', models.TextField(default=b'null', verbose_name=b'Cabe\xc3\xa7alho')),
                ('objetivo_txt', models.TextField(default=b'null', verbose_name=b'Objetivo')),
                ('participar_txt', models.TextField(default=b'null', verbose_name=b'Como participar')),
                ('resultado_txt', models.TextField(default=b'null', verbose_name=b'Resultado')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name=b'Nome do Projeto')),
                ('acronym', models.CharField(blank=True, max_length=10, verbose_name=b'Sigla')),
                ('etapa', models.CharField(default=b'1', max_length=1, verbose_name=b'Etapa')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[(b'1', b'One choice'), (b'2', b'Multipla Escolha'), (b'3', b'Texto')], max_length=1, verbose_name=b'Tipo')),
                ('question_text', models.CharField(max_length=200, verbose_name=b'T\xc3\xadtulo da Quest\xc3\xa3o')),
                ('publ_date', models.DateTimeField(verbose_name=b'Data de publica\xc3\xa7\xc3\xa3o')),
                ('exp_date', models.DateTimeField(verbose_name=b'Data de expira\xc3\xa7\xc3\xa3o')),
                ('days', models.IntegerField(choices=[(1, b'1 dia'), (7, b'1 semana'), (30, b'1 m\xc3\xaas'), (365, b'1 ano'), (3650, b'Indeterminado')], default=3650, verbose_name=b'Tempo para expirar')),
                ('question_status', models.CharField(choices=[(b'n', b'N\xc3\xa3o publicado'), (b'p', b'Publicado')], default=b'n', max_length=1, verbose_name=b'Estado da quest\xc3\xa3o')),
                ('answer_status', models.CharField(choices=[(b'n', b'N\xc3\xa3o publicado'), (b'p', b'Publicado')], default=b'n', max_length=1, verbose_name=b'Estado da resposta')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'question_images', verbose_name=b'Imagem')),
                ('address', models.CharField(max_length=200, verbose_name=b'Endere\xc3\xa7o')),
                ('permissao', models.IntegerField(default=0)),
                ('resultado', models.CharField(choices=[(b'n', b'N\xc3\xa3o publicado'), (b'p', b'Publicado')], default=b'n', max_length=1)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Project')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'quest\xe3o',
                'verbose_name_plural': 'quest\xf5es',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(default=b'media/img/no-avatar.jpg', upload_to=b'media/img/')),
                ('first_name', models.CharField(blank=True, max_length=40, verbose_name=b'Nome')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name=b'Sobrenome')),
                ('staff', models.CharField(blank=True, choices=[(b'1', b'Professor'), (b'2', b'Funcionario'), (b'3', b'Aluno-Graduacao'), (b'4', b'Aluno-Mestrado'), (b'5', b'Aluno-Doutorado'), (b'6', b'Aluno-Especial'), (b'7', b'Aluno-Lato'), (b'8', b'Outro')], max_length=1, verbose_name=b'Staff')),
                ('institute', models.CharField(blank=True, default=b'instituto', max_length=40, verbose_name=b'Instituto')),
                ('academic_registry', models.IntegerField(default=b'9999', verbose_name=b'Registro acad\xc3\xaamico')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name=b'Email')),
                ('nickname', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Apelido')),
            ],
            options={
                'verbose_name': 'Usu\xe1rio',
                'verbose_name_plural': 'Usu\xe1rios',
            },
        ),
        migrations.AddField(
            model_name='etapas',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Project', verbose_name=b'Projeto'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Question'),
        ),
    ]
