# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('primeiro_nome', models.CharField(blank=True, max_length=40, verbose_name='Primeiro nome')),
                ('ultimo_nome', models.CharField(blank=True, max_length=100, verbose_name='Sobrenome')),
                ('staff', models.CharField(blank=True, choices=[('1', 'Professor'), ('2', 'Funcionario'), ('3', 'Aluno-Graduacao'), ('4', 'Aluno-Mestrado'), ('5', 'Aluno-Doutorado'), ('6', 'Aluno-Especial'), ('7', 'Aluno-Lato'), ('8', 'outro')], max_length=1, verbose_name='Staff')),
                ('institute', models.CharField(blank=True, default='instituto', max_length=40, verbose_name='Instituto')),
                ('academic_registry', models.IntegerField(default='9999', verbose_name='Registro acad\xeamico')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nickname', models.CharField(blank=True, max_length=40, verbose_name='Apelido')),
                ('projeto', models.CharField(blank=True, max_length=40, verbose_name='Projeto')),
            ],
        ),
    ]
