# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170705_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proponent',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.User'),
            preserve_default=False,
        ),
    ]
