# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170710_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='author',
            new_name='user',
        ),
    ]
