# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170629_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Post'),
        ),
    ]
