# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_user_avatarz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatarz',
            new_name='avatar',
        ),
    ]
