# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20170713_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenthistory',
            name='text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
