# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20170714_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenthistory',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
