# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 14:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20170720_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name=b'ckeditor'),
        ),
    ]
