# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20170720_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 7, 22, 4, 42, 547228, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='replyhistory',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='mainapp.Reply'),
        ),
    ]
