# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20170807_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Data de publica\xc3\xa7\xc3\xa3o'),
        ),
    ]
