# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20170807_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Publication')),
                ('about', models.CharField(max_length=200)),
                ('choice_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='mainapp.ChoiceQuestion')),
            ],
            bases=('mainapp.publication',),
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-pub_date',)},
        ),
    ]
