# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20170809_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalsRanking',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.Publication')),
                ('about', models.CharField(max_length=200)),
            ],
            bases=('mainapp.publication',),
        ),
        migrations.CreateModel(
            name='RankedProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('victories', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('proposals_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_proposal', to='mainapp.ProposalsRanking')),
            ],
        ),
    ]
